package products

// GetSampleProducts returns a list of 50 sample products
func GetSampleProducts() []ProductData {
	return []ProductData{
		{ID: "1", Title: "Smartphone", Category: "Electronics", Brand: "Samsung"},
		{ID: "2", Title: "Laptop", Category: "Electronics", Brand: "Apple"},
		{ID: "3", Title: "Running Shoes", Category: "Footwear", Brand: "Nike"},
		{ID: "4", Title: "Tablet", Category: "Electronics", Brand: "Sony"},
		{ID: "5", Title: "Gaming Console", Category: "Electronics", Brand: "Microsoft"},
		{ID: "6", Title: "Casual Shoes", Category: "Footwear", Brand: "Adidas"},
		{ID: "7", Title: "Headphones", Category: "Electronics", Brand: "Bose"},
		{ID: "8", Title: "Backpack", Category: "Computer Accessories", Brand: "Fjällräven"},
		{ID: "9", Title: "Fitness Tracker", Category: "Fitness", Brand: "Nike"},
		{ID: "10", Title: "Sandals", Category: "Footwear", Brand: "Adidas"},
		{ID: "11", Title: "Digital Camera", Category: "Photography", Brand: "Sony"},
		{ID: "12", Title: "Sunglasses", Category: "Clothing", Brand: "Nike"},
		{ID: "13", Title: "Wireless Mouse", Category: "Computer Accessories", Brand: "Logitech"},
		{ID: "14", Title: "Hiking Boots", Category: "Footwear", Brand: "Adidas"},
		{ID: "15", Title: "External Hard Drive", Category: "Electronics", Brand: "Seagate"},
		{ID: "16", Title: "Smartwatch", Category: "Wearables", Brand: "Garmin"},
		{ID: "17", Title: "Wallet", Category: "Clothing", Brand: "Adidas"},
		{ID: "18", Title: "Bluetooth Speaker", Category: "Electronics", Brand: "Bose"},
		{ID: "19", Title: "Running Shorts", Category: "Clothing", Brand: "Nike"},
		{ID: "20", Title: "Dress Shoes", Category: "Footwear", Brand: "Adidas"},
		{ID: "21", Title: "Desktop Computer", Category: "Electronics", Brand: "Microsoft"},
		{ID: "22", Title: "Running Jacket", Category: "Clothing", Brand: "Nike"},
		{ID: "23", Title: "Travel Backpack", Category: "Computer Accessories", Brand: "Fjällräven"},
		{ID: "24", Title: "Wireless Keyboard", Category: "Computer Accessories", Brand: "Logitech"},
		{ID: "25", Title: "Camping Tent", Category: "Outdoor Gear", Brand: "REI"},
		{ID: "26", Title: "Yoga Mat", Category: "Fitness", Brand: "Adidas"},
		{ID: "27", Title: "Duffle Bag", Category: "Clothing", Brand: "Nike"},
		{ID: "28", Title: "E-reader", Category: "Electronics", Brand: "Kindle"},
		{ID: "29", Title: "Office Chair", Category: "Furniture", Brand: "Herman Miller"},
		{ID: "30", Title: "Winter Boots", Category: "Footwear", Brand: "Adidas"},
		{ID: "31", Title: "Camera Lens", Category: "Photography", Brand: "Sony"},
		{ID: "32", Title: "Gym Bag", Category: "Fitness", Brand: "Nike"},
		{ID: "33", Title: "Smart Thermostat", Category: "Electronics", Brand: "Nest"},
		{ID: "34", Title: "Coffee Maker", Category: "Electronics", Brand: "Keurig"},
		{ID: "35", Title: "Baseball Cap", Category: "Clothing", Brand: "Nike"},
		{ID: "36", Title: "Gaming Mouse", Category: "Computer Accessories", Brand: "Razer"},
		{ID: "37", Title: "Backpacking Tent", Category: "Outdoor Gear", Brand: "Big Agnes"},
		{ID: "38", Title: "Running Watch", Category: "Fitness", Brand: "Nike"},
		{ID: "39", Title: "Dress Shirt", Category: "Clothing", Brand: "Adidas"},
		{ID: "40", Title: "Portable Charger", Category: "Electronics", Brand: "Anker"},
		{ID: "41", Title: "Ski Goggles", Category: "Outdoor Gear", Brand: "Oakley"},
		{ID: "42", Title: "Wireless Earbuds", Category: "Electronics", Brand: "Sennheiser"},
		{ID: "43", Title: "Cycling Helmet", Category: "Outdoor Gear", Brand: "Bell"},
		{ID: "44", Title: "Running Hat", Category: "Clothing", Brand: "Nike"},
		{ID: "45", Title: "Bluetooth Headset", Category: "Electronics", Brand: "Plantronics"},
		{ID: "46", Title: "Dress Watch", Category: "Clothing", Brand: "Nike"},
		{ID: "47", Title: "Gaming Keyboard", Category: "Computer Accessories", Brand: "SteelSeries"},
		{ID: "48", Title: "Hiking Socks", Category: "Footwear", Brand: "Adidas"},
		{ID: "49", Title: "Digital Scale", Category: "Fitness", Brand: "Withings"},
		{ID: "50", Title: "Drip Coffee Maker", Category: "Electronics", Brand: "Cuisinart"},
		{ID: "51", Title: "Wireless Headphones", Category: "Electronics", Brand: "Sony"},
		{ID: "52", Title: "Running Backpack", Category: "Accessories", Brand: "Nike"},
		{ID: "53", Title: "Smart Speaker", Category: "Electronics", Brand: "Bose"},
		{ID: "54", Title: "Trail Running Shoes", Category: "Footwear", Brand: "Adidas"},
		{ID: "55", Title: "Compact Camera", Category: "Photography", Brand: "Canon"},
		{ID: "56", Title: "Gaming Laptop", Category: "Electronics", Brand: "Microsoft"},
		{ID: "57", Title: "Fitness Band", Category: "Wearables", Brand: "Fitbit"},
		{ID: "58", Title: "Winter Jacket", Category: "Clothing", Brand: "Columbia"},
		{ID: "59", Title: "Gaming Mousepad", Category: "Computer Accessories", Brand: "Logitech"},
		{ID: "60", Title: "Running Tights", Category: "Clothing", Brand: "Under Armour"},
		{ID: "61", Title: "In-ear Earphones", Category: "Electronics", Brand: "Samsung"},
		{ID: "62", Title: "Office Backpack", Category: "Accessories", Brand: "Fjällräven"},
		{ID: "63", Title: "Digital Watch", Category: "Wearables", Brand: "Garmin"},
		{ID: "64", Title: "Hiking Shoes", Category: "Footwear", Brand: "Merrell"},
		{ID: "65", Title: "Portable Hard Drive", Category: "Electronics", Brand: "Seagate"},
		{ID: "66", Title: "Bluetooth Earbuds", Category: "Electronics", Brand: "JBL"},
		{ID: "67", Title: "Travel Shoes", Category: "Footwear", Brand: "Teva"},
		{ID: "68", Title: "Mirrorless Camera", Category: "Photography", Brand: "Sony"},
		{ID: "69", Title: "Gaming Headset", Category: "Electronics", Brand: "SteelSeries"},
		{ID: "70", Title: "Casual Backpack", Category: "Accessories", Brand: "Herschel"},
		{ID: "71", Title: "Running Gloves", Category: "Clothing", Brand: "Nike"},
		{ID: "72", Title: "Mechanical Keyboard", Category: "Computer Accessories", Brand: "Corsair"},
		{ID: "73", Title: "Trekking Poles", Category: "Outdoor Gear", Brand: "REI"},
		{ID: "74", Title: "Fitness Gloves", Category: "Fitness", Brand: "Under Armour"},
		{ID: "75", Title: "Wireless Charging Pad", Category: "Electronics", Brand: "Samsung"},
		{ID: "76", Title: "Trail Running Shorts", Category: "Clothing", Brand: "Adidas"},
		{ID: "77", Title: "Gaming Chair", Category: "Furniture", Brand: "Dell"},
		{ID: "78", Title: "Cycling Shoes", Category: "Footwear", Brand: "Nike"},
		{ID: "79", Title: "External SSD", Category: "Electronics", Brand: "Samsung"},
		{ID: "80", Title: "Wool Socks", Category: "Clothing", Brand: "Smartwool"},
		{ID: "81", Title: "Smart Lock", Category: "Home Automation", Brand: "Nest"},
		{ID: "82", Title: "Travel Pillow", Category: "Accessories", Brand: "Patagonia"},
		{ID: "83", Title: "Wireless Gaming Mouse", Category: "Computer Accessories", Brand: "Razer"},
		{ID: "84", Title: "Trail Running Hat", Category: "Clothing", Brand: "Nike"},
		{ID: "85", Title: "Waterproof Backpack", Category: "Accessories", Brand: "Fjällräven"},
		{ID: "86", Title: "Compact Binoculars", Category: "Outdoor Gear", Brand: "Nikon"},
		{ID: "87", Title: "Gaming Monitor", Category: "Electronics", Brand: "Samsung"},
		{ID: "88", Title: "Running Socks", Category: "Clothing", Brand: "Nike"},
		{ID: "89", Title: "Smart Home Camera", Category: "Home Automation", Brand: "Ring"},
		{ID: "90", Title: "Winter Gloves", Category: "Clothing", Brand: "Columbia"},
		{ID: "91", Title: "Gaming Desk", Category: "Furniture", Brand: "IKEA"},
		{ID: "92", Title: "Camping Stove", Category: "Outdoor Gear", Brand: "Coleman"},
		{ID: "93", Title: "Wrist Weights", Category: "Fitness", Brand: "Nike"},
		{ID: "94", Title: "Wireless Gaming Headset", Category: "Electronics", Brand: "Logitech"},
		{ID: "95", Title: "Travel Mug", Category: "Accessories", Brand: "Yeti"},
		{ID: "96", Title: "Hydration Pack", Category: "Outdoor Gear", Brand: "CamelBak"},
		{ID: "97", Title: "Dumbbell Set", Category: "Fitness", Brand: "Bowflex"},
		{ID: "98", Title: "Bluetooth Car Kit", Category: "Electronics", Brand: "Anker"},
		{ID: "99", Title: "Running Headlamp", Category: "Outdoor Gear", Brand: "Black Diamond"},
		{ID: "100", Title: "Portable Blender", Category: "Kitchen Appliances", Brand: "Vitamix"},
	}
}
